### ISSUE TITLE
publish talk?

### ISSUE THREAD

**Issue by bradfitz** [RaitoBezarius/nixops-proxmox#1]
Looks like this talk already happened?

https://cfp.nixcon.org/nixcon2020/talk/7RKBTE/

The README suggests (https://github.com/RaitoBezarius/nixops-proxmox#nixops-plugin-for-proxmox) that you were going to publish the talk afterwards. This is a track bug to remind you to do so! 😃

**Comment by bradfitz** [comment]
cc @danderson too, who I'm sure would be interested.

**Comment by RaitoBezarius** [comment]
Oh sorry for the delay @bradfitz the talk was supposedly published on the CFP system, otherwise, it's here: https://github.com/RaitoBezarius/nixops-proxmox/tree/master/meta/nixcon_2020 !

**Comment by LennyPenny** [comment]
there's also a recording here https://av.tib.eu/media/50060
